export const CHECKLIST = [
  { id: 'trailer', title: 'Trailer Prep', items: [
    { id: 'tr1',  text: 'Place mats', def: true },
    { id: 'tr2',  text: 'Water heater (dewinterized + troubleshot)', def: true },
    { id: 'tr3',  text: 'Refrigerator working', def: true },
    { id: 'tr4',  text: 'Oil, salt, pan, spatula', def: true },
    { id: 'tr5',  text: 'Eggs, tortillas', def: true },
    { id: 'tr6',  text: 'Tire pressure checked' },
    { id: 'tr7',  text: 'Propane checked' },
    { id: 'tr8',  text: 'Organize hose' },
    { id: 'tr9',  text: 'Water jugs filled' },
    { id: 'tr10', text: 'Short work list completed' },
  ]},
  { id: 'bike_done', title: 'Bike — Already Done', items: [
    { id: 'bd1',  text: 'New chain installed (SRAM XO Flattop)', def: true },
    { id: 'bd2',  text: 'MTX ceramic brake pads — front and rear (1 ride)', def: true },
    { id: 'bd3',  text: 'Barzo 29x2.4 TLR mounted front — sealant fresh', def: true },
    { id: 'bd4',  text: 'Mezcal 29x2.4 TLR mounted rear', def: true },
    { id: 'bd5',  text: 'Tire pressure set: Barzo 16psi / Mezcal 18psi', def: true },
    { id: 'bd6',  text: 'Fork sag set — Pike Ultimate 130mm (63psi → 62psi)', def: true },
    { id: 'bd7',  text: 'Rear shock set — Deluxe Ultimate (153psi)', def: true },
    { id: 'bd8',  text: 'All bolts retorqued to spec', def: true },
    { id: 'bd9',  text: "Drivetrain clean — shifting best it's been", def: true },
    { id: 'bd10', text: 'Dropper post lubed', def: true },
    { id: 'bd11', text: 'Freehub lubed (Dumond Tech)', def: true },
    { id: 'bd12', text: 'Deep clean after Sun Valley mud ride', def: true },
  ]},
  { id: 'bike_week', title: 'Bike — This Week', items: [
    { id: 'bw1',  text: 'Mechanic visit — chainstay guard secured, brake cable shortened' },
    { id: 'bw2',  text: 'Confirm brake bed-in ride post-mechanic (minimum 1)' },
    { id: 'bw3',  text: 'Minimum 2 more rides on Barzo before race day' },
    { id: 'bw4',  text: 'AXS derailleur battery — full charge confirmed race morning' },
    { id: 'bw5',  text: 'AXS spare battery — fully charged, staged with Renee' },
    { id: 'bw6',  text: 'Check AXS firmware current on all components (AXS app)' },
    { id: 'bw7',  text: 'Garmin 540 — screen layout confirmed (3s power / lap avg / HR zone / lap timer)' },
    { id: 'bw8',  text: 'Garmin 540 — 2026 course GPX loaded' },
    { id: 'bw9',  text: 'Garmin 540 — auto-lap GPS trigger set at start/finish coordinate' },
    { id: 'bw10', text: 'Wash bike before loading' },
  ]},
  { id: 'gear', title: 'Gear', items: [
    { id: 'g1',  text: 'Lost River race kit' },
    { id: 'g2',  text: 'Helmet' },
    { id: 'g3',  text: 'Gloves' },
    { id: 'g4',  text: 'Shoes + socks' },
    { id: 'g5',  text: 'Sunglasses — clear lens staged for evening laps' },
    { id: 'g6',  text: 'HRM strap' },
    { id: 'g7',  text: 'Chamois cream (apply race morning)' },
    { id: 'g8',  text: 'Sunscreen (apply race morning)' },
    { id: 'g9',  text: 'Training kits' },
    { id: 'g10', text: 'Training tires (on training wheels)' },
    { id: 'g11', text: 'Waist pack if needed' },
  ]},
  { id: 'layers', title: 'Layer Kit (staged with Renee)', items: [
    { id: 'l1', text: 'Wind vest' },
    { id: 'l2', text: 'Arm warmers' },
    { id: 'l3', text: 'Rain jacket' },
    { id: 'l4', text: 'Light gloves' },
    { id: 'l5', text: 'Emergency base layer' },
  ]},
  { id: 'pitbag', title: 'Mechanical / Pit Bag (Renee)', items: [
    { id: 'pb1', text: 'Spare tubes x2' },
    { id: 'pb2', text: 'Tubeless plug kit' },
    { id: 'pb3', text: 'Sealant top-up bottle' },
    { id: 'pb4', text: 'CO2 x3 + inflator' },
    { id: 'pb5', text: 'SRAM Flattop quick links x2' },
    { id: 'pb6', text: 'Multi-tool' },
    { id: 'pb7', text: 'AXS spare battery (fully charged)' },
    { id: 'pb8', text: 'Spare MTX brake pads' },
    { id: 'pb9', text: 'Tire levers x2' },
  ]},
  { id: 'onbike', title: 'On-Bike Kit', items: [
    { id: 'ob1', text: 'Tubeless plugs' },
    { id: 'ob2', text: 'CO2 x1' },
    { id: 'ob3', text: 'Multi-tool' },
    { id: 'ob4', text: 'Quick link x1' },
  ]},
  { id: 'nutrition', title: 'Nutrition', items: [
    { id: 'n1', text: 'Formula 369 — enough for 10+ large bottles (2 scoops each)' },
    { id: 'n2', text: 'Maurten gels — 8 regular + 3 caffeine (separate caffeine gels)' },
    { id: 'n3', text: 'Plain water bottles x2 staged at pit' },
    { id: 'n4', text: 'Post-race recovery nutrition staged' },
    { id: 'n5', text: 'Race morning snack for drive if needed' },
  ]},
  { id: 'renee_fri', title: 'Renee — Friday Night at Donnelly', items: [
    { id: 'rf1', text: 'Pre-mix all Formula 369 bottles — label Large-2sc / Water' },
    { id: 'rf2', text: 'Separate and label caffeine gels (max 3, laps 5–7)' },
    { id: 'rf3', text: 'Inventory layer kit — confirm all items present' },
    { id: 'rf4', text: 'Confirm pit bag contents against mechanical list' },
    { id: 'rf5', text: 'Charge Garmin 540 fully' },
    { id: 'rf6', text: 'Charge AXS spare battery fully' },
    { id: 'rf7', text: 'Breakfast prep ready for 6:30am (burrito ingredients)' },
    { id: 'rf8', text: 'Review PitSync app and signal vocabulary with Andrew' },
    { id: 'rf9', text: 'Review one-word signals: GOOD / ADJUST / WATER / LAYERS / BATTERY / MECH' },
  ]},
  { id: 'food', title: 'Food — Carb Load', items: [
    { id: 'f1', text: 'Mon–Wed: Normal clean food, stay well hydrated' },
    { id: 'f2', text: 'Thu–Fri: Increase carbs at every meal (rice, pasta, potatoes, bread)' },
    { id: 'f3', text: 'Thu–Fri: No new foods, no alcohol' },
    { id: 'f4', text: 'Race morning: Breakfast burrito — 4 eggs, meat, rice, 2 tortillas' },
    { id: 'f5', text: 'Race morning: Coffee' },
  ]},
  { id: 'fri_travel', title: 'Friday June 12 — Travel Day', items: [
    { id: 'ft1',  text: 'Load bike on rack — confirm secure' },
    { id: 'ft2',  text: 'Secure 4Runner cover' },
    { id: 'ft3',  text: 'Load trailer — gear, nutrition, pit bag' },
    { id: 'ft4',  text: 'Tool kit loaded' },
    { id: 'ft5',  text: 'Depart — target Donnelly arrival 2:30pm' },
    { id: 'ft6',  text: 'Hook up at Donnelly RV Park (full hookups)' },
    { id: 'ft7',  text: 'Drive to JMR — packet pickup opens 5pm' },
    { id: 'ft8',  text: 'Claim pit spot at start/finish area' },
    { id: 'ft9',  text: 'Set up triangle shade cloth' },
    { id: 'ft10', text: 'Preview lap — ride slow, focus on Vandelay entry and lines' },
    { id: 'ft11', text: 'Note tightest corners and line choices on Vandelay' },
    { id: 'ft12', text: 'Back to Donnelly — dinner, early bed' },
  ]},
  { id: 'sat_morning', title: 'Saturday June 13 — Race Morning', items: [
    { id: 'sm1',  text: 'Wake up 6:00am' },
    { id: 'sm2',  text: 'Breakfast burrito + coffee' },
    { id: 'sm3',  text: 'Chamois cream + sunscreen applied' },
    { id: 'sm4',  text: 'Tire pressure confirmed: Barzo 16psi / Mezcal 18psi' },
    { id: 'sm5',  text: 'Garmin 540 charged and ready' },
    { id: 'sm6',  text: 'AXS battery confirmed full' },
    { id: 'sm7',  text: 'Depart Donnelly 7:15am' },
    { id: 'sm8',  text: 'Arrive JMR 7:45am — final pit setup with Renee' },
    { id: 'sm9',  text: 'Warmup 8:00–8:45am: easy spin + 2–3 × 30sec openers ~220W' },
    { id: 'sm10', text: 'Stage 8:50am' },
    { id: 'sm11', text: 'Race start 9:00am' },
  ]},
  { id: 'post_race', title: 'Post-Race', items: [
    { id: 'pr1', text: 'Podium + raffle 5:30pm at start/finish' },
    { id: 'pr2', text: 'Dinner on site (registered ✓ — Renee included)' },
    { id: 'pr3', text: 'Download Garmin activity' },
    { id: 'pr4', text: 'Note what worked / what to adjust for Enchanted Forest' },
  ]},
  { id: 'todo', title: 'To Do — General', items: [
    { id: 'td1', text: 'Sprinkler repair (home)' },
    { id: 'td2', text: 'Laundry' },
    { id: 'td3', text: 'Pack clothes' },
    { id: 'td4', text: 'Load bike gear' },
    { id: 'td5', text: 'Secure rack' },
    { id: 'td6', text: 'Cover 4Runner' },
    { id: 'td7', text: 'Plan confirmed with Renee' },
  ]},
];

export function buildDefaultClState(checklist) {
  const state = {};
  checklist.forEach(s => s.items.forEach(item => { state[item.id] = item.def === true; }));
  return state;
}

export function countChecklist(checklist, state) {
  let total = 0, done = 0;
  checklist.forEach(s => s.items.forEach(item => { total++; if (state[item.id]) done++; }));
  return { total, done };
}
